function stats(v){
  const now=Date.now(),sd=startDay(),rl=S.log.filter(l=>l.rv&&l.t>now-30*DAY);
  const tr=rl.length?Math.round(100*rl.filter(l=>l.g>1).length/rl.length):null;
  const g=$('div',{className:'c'},'<h2>Umumiy</h2>');const gr=$('div',{className:'stats'});
  const dueN=S.cards.filter(c=>c.s&&c.due<=now).length;
  [[S.cards.length,'Jami kartalar'],[dueN,'Hozir takrorlash kerak'],[S.cards.filter(c=>c.s&&c.s>=21).length,'Mustahkam (21+ kun)'],[tr===null?'—':tr+'%','Haqiqiy eslab qolish (30 kun)'],[S.log.filter(l=>l.t>=sd).length,'Bugun takrorlangan'],[S.cards.filter(c=>!c.s).length,'Yangi']].forEach(([n,t])=>gr.appendChild($('div',{className:'stat'},`<b>${n}</b><span>${t}</span>`)));
  g.appendChild(gr);v.appendChild(g);
  const f=$('div',{className:'c'},'<h2>Keyingi 7 kun prognozi</h2>');const bars=$('div',{className:'bars'});
  const cnt=[...Array(7)].map((_,i)=>S.cards.filter(c=>c.s&&(i===0?c.due<sd+DAY:c.due>=sd+i*DAY&&c.due<sd+(i+1)*DAY)).length),mx=Math.max(1,...cnt);
  cnt.forEach((n,i)=>bars.appendChild($('div',{},`${n}<i style="height:${Math.round(n/mx*60)}px"></i>${i?'+'+i:'bugun'}`)));
  f.appendChild(bars);v.appendChild(f);
  const days=new Set(S.log.map(l=>new Date(l.t).toDateString()));let st=0,dd=new Date();if(!days.has(dd.toDateString()))dd.setDate(dd.getDate()-1);while(days.has(dd.toDateString())){st++;dd.setDate(dd.getDate()-1)}
  const lc=S.cards.filter(c=>(c.lapses||0)>=3).sort((a,b)=>b.lapses-a.lapses);
  const k=$('div',{className:'c'},`<h2>🔥 Seriya: ${st} kun</h2><h2 style="margin-top:12px">Qiyin kartalar (${lc.length})</h2>`);
  lc.slice(0,10).forEach(c=>{const r=$('div',{className:'row'}),s2=$('span');s2.textContent=c.q+' — '+c.lapses+' marta xato';r.appendChild(s2);k.appendChild(r)});
  v.appendChild(k);
  const t0=new Date();t0.setHours(0,0,0,0);const dc={};S.log.forEach(l=>{const k=new Date(l.t).toDateString();dc[k]=(dc[k]||0)+1});
  const hm=$('div',{className:'c'},'<h2>Faollik (oxirgi 105 kun)</h2>');const gw=$('div',{style:'display:grid;grid-template-rows:repeat(7,1fr);grid-auto-flow:column;gap:4px'});
  for(let i=104;i>=0;i--){const d=new Date(t0);d.setDate(d.getDate()-i);const n=dc[d.toDateString()]||0;gw.appendChild($('div',{title:d.toLocaleDateString()+': '+n,style:'aspect-ratio:1;border-radius:4px;background:'+(n?'linear-gradient(135deg,var(--g1),var(--g2))':'var(--bd)')+';opacity:'+(n?Math.min(1,.35+n/40):1)}))}
  hm.appendChild(gw);v.appendChild(hm);
  const tot=S.log.length,mat=S.cards.filter(c=>c.s>=21).length;
  const ac=$('div',{className:'c'},'<h2>Yutuqlar</h2>');
  [['🌱','Birinchi takror',tot>=1],['🔥','7 kunlik seriya',st>=7],['📚','100 ta karta',S.cards.length>=100],['💎','25 ta mustahkam',mat>=25],['🏆','1000 takror',tot>=1000],['🧠','Eslab qolish 90%+',tr!==null&&tr>=90]].forEach(([e,n,ok])=>ac.appendChild($('span',{style:'display:inline-block;margin:0 6px 6px 0;padding:7px 14px;border-radius:99px;border:1px solid var(--bd);font-size:13px;opacity:'+(ok?1:.35)},e+' '+n)));
  v.appendChild(ac);
  const rp=$('div',{className:'c'},'<h2>✨ Haftalik hisobot (AI)</h2>');const rt=$('div',{className:'sub',style:'white-space:pre-wrap;margin-bottom:10px'});
  const rb=$('button',{className:'btn',onclick:async()=>{rb.textContent='Tahlil qilinmoqda...';try{const w=S.log.filter(l=>l.t>now-7*DAY);const r=await askAI('report',{data:{reviews7:w.length,correct7:w.filter(l=>l.g>1).length,streak:st,cards:S.cards.length,mature:mat,hardCards:lc.slice(0,5).map(c=>c.q),retention30:tr}});rt.textContent=r.t;rb.textContent='Qayta yaratish'}catch(e){alert(e.message);rb.textContent='Hisobot yaratish'}}});rb.textContent='Hisobot yaratish';rp.append(rt,rb);v.appendChild(rp);
  const io=$('div',{className:'c'},'<h2>Import va ulashish</h2><div class="hint" style="margin-bottom:8px">CSV yoki TXT (Anki: "Notes in Plain Text"). Har qatorda savol va javob.</div>');
  const fi=$('input',{type:'file',accept:'.csv,.txt,.tsv',onchange:async e=>{const t=await e.target.files[0].text();let n=0;t.split(/\r?\n/).forEach(l=>{if(l.startsWith('#'))return;const p=l.split(l.includes('\t')?'\t':l.includes(';')?';':',');if(p.length>=2&&p[0].trim()&&p[1].trim()){S.cards.push({id:Date.now()+Math.random(),q:p[0].trim(),a:p[1].trim(),mod:Date.now()});n++}});save();alert(n+' ta karta import qilindi');render()}});
  const sh=$('button',{className:'btn',onclick:()=>{const d=S.cards.slice(0,100).map(c=>[c.q,c.a,c.tag||'']);const u=location.origin+'/#d='+btoa(unescape(encodeURIComponent(JSON.stringify(d))));navigator.clipboard.writeText(u).then(()=>alert('Havola nusxalandi ('+d.length+' karta)'))}});sh.textContent='Kartalarni havola orqali ulashish';
  io.append(fi,sh);v.appendChild(io);
  const s=$('div',{className:'c'},'<h2>Sozlamalar</h2>');
  s.appendChild($('div',{className:'hint'},'Maqsadli eslab qolish: '+Math.round(S.ret*100)+'% (yuqori = koʻproq takror)'));
  const r=$('input',{type:'range',min:70,max:97,value:S.ret*100,oninput:e=>{S.ret=e.target.value/100;save();s.firstChild.nextSibling.textContent='Maqsadli eslab qolish: '+e.target.value+'% (yuqori = koʻproq takror)'}});
  const n=$('input',{type:'number',min:0,max:200,value:S.newLim,onchange:e=>{S.newLim=+e.target.value;save()}});
  s.append(r,$('div',{className:'hint'},'Kuniga yangi kartalar:'),n);
  const tp=$('label',{className:'hint',style:'display:block;margin:8px 0'},'<input type="checkbox" style="width:auto;margin-right:6px" '+(S.typed?'checked':'')+'> Javobni yozib tekshirish');tp.firstChild.onchange=e=>{S.typed=e.target.checked;save()};
  const lg=$('input',{value:S.lang,placeholder:'en-US, ru-RU, tr-TR',onchange:e=>{S.lang=e.target.value||'en-US';save()}});
  const cb=$('button',{className:'btn',style:'margin:8px 0',onclick:calib});cb.textContent='Intervallarni oʻz tariximga moslash';
  s.append(tp,$('div',{className:'hint'},'Ovoz tili (🔊 tugmasi uchun):'),lg,cb);
  const sy=$('div',{className:'hint',style:'margin-top:10px'},'<b>Sinxronlash:</b> '+(S.key?'yoqilgan':'oʻchiq')+'<br>Kalit (boshqa qurilmaga shuni kiriting):');
  const ki=$('input',{value:S.key||'',placeholder:'Sinxronlash kaliti',onchange:e=>{S.key=e.target.value.trim();save();sync()}});
  const nk=$('button',{className:'btn',style:'margin:6px 0',onclick:()=>{S.key=crypto.randomUUID()+crypto.randomUUID();save();sync();render()}});nk.textContent='Yangi kalit yaratish va yoqish';
  const pb=$('button',{className:'btn',style:'margin:6px 0',onclick:pushOn});pb.textContent='🔔 Kunlik eslatmani yoqish';
  const mxl=$('label',{className:'hint',style:'display:block;margin:8px 0'},'<input type="checkbox" style="width:auto;margin-right:6px" '+(S.mix?'checked':'')+'> Takrorlashda kartalarni aralashtirish');mxl.firstChild.onchange=e=>{S.mix=e.target.checked;save()};
  s.append(mxl,sy,ki,nk,pb);
  const sec=$('div',{className:'sec'});
  const ex=$('button',{onclick:()=>{const a=$('a',{href:'data:application/json;charset=utf-8,'+encodeURIComponent(JSON.stringify(S)),download:'zaxira.json'});a.click()}});ex.textContent='Zaxira (JSON)';
  const im=$('button',{onclick:()=>{const t=prompt('Zaxira JSON matnini qoʻying:');if(t)try{S=Object.assign(S,JSON.parse(t));save();render()}catch(e){alert('Xato format')}}});im.textContent='Tiklash';
  sec.append(ex,im);s.appendChild(sec);v.appendChild(s);
  v.appendChild($('div',{className:'hint'},'Algoritm: FSRS-5 (Anki 23.10+ da ham bor). Har karta uchun Qiyinlik, Barqarorlik va Eslab qolish ehtimoli hisoblanadi.'));
}